### ISSUE TITLE
The Next, Prev, Parent and Root links next to comments seem to have disappeared.

### ISSUE THREAD

**Issue by evmcl** [insin/hn-comments-owl#20]
The Next, Prev, Parent and Root links next to comments seem to have disappeared.

**Comment by insin** [comment]
This was done as muting can break them - I'll add an option to control whether you want them hidden or not (default: not hidden) and fix the next/prev links as part of #18 

- [ ] Add an option to control display of next/prev comment nav links

**Comment by evmcl** [comment]
Okay. Tbh I use the Parent and Root links a lot more, so as long as those are back, I'll be happy.
