### ISSUE TITLE
Option for "Don't collapse threads without new comments"

### ISSUE THREAD

**Issue by NewsGuyTor** [insin/hn-comments-owl#8]
Great userscript!

However I'd like an option to don't collapse threads without new comments.

For now I've just removed the code block, but that's not a very good solution. An option would be much better.

**Comment by spiralx** [comment]
Agreed, the feature is useful coming back to a thread you've visited before, but super annoying when you've replied to a comment or gone to a second page in a very large thread.

Will also switch to the user script, good idea :)

**Comment by insin** [comment]
Implemented in 467505c1ffccd774bd0c27d67a56964994648af3, used the wrong issue number in the commit message 🤦
