### ISSUE TITLE
Seems to have stopped working

### ISSUE THREAD

**Issue by evmcl** [insin/hn-comments-owl#9]
As of today this plugin seems to have stopped working.

Looking at console output, I'm wondering if HN changed their Content-Security-Policy header and that's what broke it. (That's purely speculation, it could be something else entirely.)

**Comment by evmcl** [comment]
Odd, it seems to be working on certain pages, but not others.

**Comment by insin** [comment]
Looks like the markup around the item metadata at the top of the page changed, so it's not getting the number of comments any more, which is half-breaking it.
